add arm64 pack workflows

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,5 +1,5 @@
 name: Test Release
-run-name: ${{ github.actor }} build ${{ github.ref_name }} ${{ github.sha }}
+run-name: ${{ github.ref_name }} ${{ github.sha }}
 
 permissions:
   contents: write
@@ -15,13 +15,39 @@ on:
         required: true
         type: boolean
         default: false
+env:
+  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  target_version: "1.10.2"
+  this_pack_manifest_version: "1.10.2-2"
 jobs:
-  job_to_build_appstore_package:
+  setup:
     runs-on: ubuntu-latest
-    env:
-      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-      release_ver: "1.10.2"
-      pkg_ver: "1.10.2-1"
+    outputs:
+      target_version: ${{ env.target_version }}
+      this_pack_manifest_version: ${{ env.this_pack_manifest_version }}
+    steps:
+      - run: echo "All set!"
+  pack-amd64:
+    uses: ./.github/workflows/pack_amd64.yml
+    secrets: inherit
+    needs:
+      - setup
+    with:
+      target_version: ${{ needs.setup.outputs.target_version }}
+      this_pack_manifest_version: ${{ needs.setup.outputs.this_pack_manifest_version }}
+  pack-arm64:
+    uses: ./.github/workflows/pack_arm64.yml
+    secrets: inherit
+    needs:
+      - setup
+    with:
+      target_version: ${{ needs.setup.outputs.target_version }}
+      this_pack_manifest_version: ${{ needs.setup.outputs.this_pack_manifest_version }}
+  upload-package:
+    runs-on: ubuntu-latest
+    needs:
+      - pack-amd64
+      - pack-arm64
     steps:
      - name: Check out repository code
        uses: actions/checkout@v4
@@ -29,27 +55,7 @@ jobs:
        run: |
          pwd
          ls -l
-     - name: 下载压缩文件
-       run: |
-         wget https://github.com/prometheus/node_exporter/releases/download/v${{ env.release_ver }}/node_exporter-${{ env.release_ver }}.linux-amd64.tar.gz
-     - name: 解压压缩文件
-       run: |
-         tar -zxvf node_exporter-${{ env.release_ver }}.linux-amd64.tar.gz
-     - name: 移动node_exporter可执行文件
-       run: |
-         mv node_exporter-${{ env.release_ver }}.linux-amd64/node_exporter ./app/node_exporter
-     - name: 打包app.tgz
-       run: |
-         tar zcvf app.tgz app ui
-         mv app.tgz node_exporter/
-     - name: 打包package
-       run: |
-         tar zcvf appstore.prometheus.node_exporter.${{ env.pkg_ver }}.tgz node_exporter
-     - name: 上传应用包
-       uses: actions/upload-artifact@master
-       with:
-         name: appstore.prometheus.node_exporter.${{ env.pkg_ver }}.tgz
-         path: appstore.prometheus.node_exporter.${{ env.pkg_ver }}.tgz
+
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
@@ -76,9 +82,9 @@ jobs:
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
-         tag_name: ${{ env.pkg_ver }}
+         tag_name: ${{ env.this_pack_manifest_version }}
          prerelease: true
-         release_name: "fnnas.appstore.prometheus.node_exporter.${{ env.pkg_ver }}"
+         release_name: "fnnas.appstore.prometheus.node_exporter.${{ env.this_pack_manifest_version }}"
 
      - name: Upload Release Assets
        if: ${{ inputs.make_release }}
@@ -90,13 +96,15 @@ jobs:
          # Upload all files in the release-assets directory
          for file in ./release-assets/*; do
            echo "Uploading $file"
-           gh release upload "${{ env.pkg_ver }}" "$file" || echo "Failed to upload $file"
+           gh release upload "${{ env.this_pack_manifest_version }}" "$file" || echo "Failed to upload $file"
          done
          
          echo "Upload completed!"
 
      - name: Verify Uploaded Assets
+       env:
+         GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ inputs.make_release }}
        run: |
          echo "Uploaded assets:"
-         gh release view "${{ env.pkg_ver }}" --json assets -q '.assets[].name'
+         gh release view "${{ env.this_pack_manifest_version }}" --json assets -q '.assets[].name'
